server:
  port: 8085

spring:
  application:
    name: legacy-adapter-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

legacy:
  soap:
    url: ${LEGACY_SOAP_URL}
