server:
  port: 8085

spring:
  application:
    name: legacy-adapter-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bankino

legacy:
  soap:
    url: ${LEGACY_SOAP_URL}
