spring:
  application:
    name: legacy-adapter-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bankino

server:
  port: 8085

legacy:
  soap:
    url: http://localhost:8086/ws
