apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-adapter

  labels:
    app: legacy-adapter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: legacy-adapter
  template:
    metadata:
      labels:
        app: legacy-adapter
    spec:
      containers:
        - name: legacy-adapter
          # Using the specific image tag from your screenshot
          image: 342547628532.dkr.ecr.us-west-2.amazonaws.com/ebanking:legacy-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            # 1. CONNECTS TO THE CORE SERVICE
            - name: LEGACY_SOAP_URL
              value: "http://core-banking-service:80/ws"

---
apiVersion: v1
kind: Service
metadata:
  name: legacy-adapter-public
  namespace: banking-ns
spec:
  # Creates an AWS Load Balancer to make this accessible from the internet
  type: LoadBalancer
  selector:
    app: legacy-adapter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085